string  cuuid       # UUID string of the SPA component.
string  xuuid       # UUID string of the xTEDS.
uint16  dialogId
uint8   requestType # Indicator for which field to use in the request
---
uint8[] xuuid       # Serialized UUID of the xTEDS.
uint16  dialogId
uint8   replyStatus # Indicate whether xTEDS was successfully found
string  xteds
